name: Deploy to Render

on:
  push:
    branches:
      - main  # or the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'  # or your specific Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to Render
      run: |
        curl -X POST "https://api.render.com/v1/services/srv-crc8nt0gph6c738qhk10/deploys" \
          -H "Accept: application/json" \
          -H "Authorization: Bearer rnd_LVb88qlfK65w0i9cblAjAn0GZYST" \
          -d '{"triggered_by": "GitHub Actions"}'
